version: 0.2
phases:
  deploy:
    commands:
      - ls -a
      - ls "frontend/dist"
      - chmod +x ./infrastructure/sam_dls.sh
      - ./infrastructure/sam_dls.sh deploy
        
  post_deploy:
    commands:
      - echo "$CODEPIPELINE_NAME"
      - aws codepipeline disable-stage-transition --pipeline-name $CODEPIPELINE_NAME --stage-name Deploy --transition-type Inbound --reason Mannual-approval-required

   
