version: 0.2
phases:
  install:
      runtime-versions:
        nodejs: 18
      commands:
        - echo "Checking if dependencies need to be installed..."
        - |
          if test -e "/root/.cache/dependencies-installed";then
          echo "dependencies already installed"
          else
          echo installing dependencies
          node -v
          npm run install:frontend
          npm run install:server
          echo "Marking dependencies as installed..."
          mkdir -p /root/.cache
          touch /root/.cache/dependencies-installed
          fi
  build:
    commands:
      - echo $STAGE_NAME
      - chmod +x ./infrastructure/sam_dls.sh
      - |
        if [ "$STAGE_NAME" == "BUILD" ]; then
          echo "Running build-specific commands"
          ./infrastructure/sam_dls.sh build 
          ./infrastructure/sam_dls.sh package
        elif [ "$STAGE_NAME" == "DEPLOY" ]; then
          echo "Running deploy-specific commands"
          ./infrastructure/sam_dls.sh deploy 
        else
          echo "Unknown stage"
          exit 1
        fi

artifacts:
  files: 
    - '**/*'
  name: MyBuildArtifacts
  discard-paths: yes

cache:
  paths:
    - '/root/.cache'