---
AWSTemplateFormatVersion: 2010-09-09
Description: "CI/CD Pipeline for AWS Serverless App"

Parameters:
  GithubToken:
    Default: invalid_token
    Description: "Github OAuth Token with full permissions on admin:repo_hook and repo"
    NoEcho: true
    Type: String

Resources:
  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: sambhav-test-cb
      Description: "AWS serverless App Code Build Project"
      ServiceRole: arn:aws:iam::189731456380:role/service-role/codebuild-sambhav-test-cb-service-role
      TimeoutInMinutes: 20
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/buildspec.yaml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: ARM_CONTAINER
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0
        PrivilegedMode: true
        ComputeType: BUILD_GENERAL1_SMALL
        

  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: sambhav-test-codepipeline
      RoleArn: arn:aws:iam::189731456380:role/service-role/AWSCodePipelineServiceRole-us-east-1-sambhav-test-pipeline
      ArtifactStore:
        Location: sambhav-test-cb-artifacts
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCodeRepo
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Branch: main
                OAuthToken: !Ref GithubToken
                Owner: sambhavgupta13
                Repo: aws-serverless-app
              OutputArtifacts:
                - Name: SourceCodeAsZip
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildProject
                EnvironmentVariables: '[{"name":"STAGE_NAME","value":"BUILD","type":"PLAINTEXT"}]'
              InputArtifacts:
                - Name: SourceCodeStageAsZip
              OutputArtifacts:
                - Name: BuildArtifactStageAsZip
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildProject
                EnvironmentVariables: '[{"name":"STAGE_NAME","value":"DEPLOY","type":"PLAINTEXT"}]'
              InputArtifacts:
                - Name: BuildArtifactAsZip
              OutputArtifacts:
                - Name: DeployArtifactAsZip
              
        
                  

