---
AWSTemplateFormatVersion: 2010-09-09
Description: "CI/CD Pipeline for AWS Serverless App"

Parameters:
  PipelineProjectName:
    Default: sambhav-test-codepipeline
    Description: "Project name for code pipeline"
    Type: String

Resources:
  CodeBuildProjectBuildStage:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: sambhav-test-cb-build-stage
      Description: "AWS serverless App Code Build Project"
      ServiceRole: arn:aws:iam::189731456380:role/service-role/codebuild-sambhav-test-cb-service-role
      TimeoutInMinutes: 20
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/buildspec-build.yaml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: ARM_CONTAINER
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0
        PrivilegedMode: true
        ComputeType: BUILD_GENERAL1_SMALL

  CodeBuildProjectDeployStage:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: sambhav-test-cb-deploy-stage
      Description: "AWS serverless App Code Build Project"
      ServiceRole: arn:aws:iam::189731456380:role/service-role/codebuild-sambhav-test-cb-service-role
      TimeoutInMinutes: 20
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/buildspec-deploy.yaml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: ARM_CONTAINER
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0
        PrivilegedMode: true
        ComputeType: BUILD_GENERAL1_SMALL

  CodeStarConnection:  
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: "sambhav-test-connection-2"
      ProviderType: GitHub


  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Ref PipelineProjectName
      RoleArn: arn:aws:iam::189731456380:role/service-role/AWSCodePipelineServiceRole-us-east-1-sambhav-test-pipeline
      ArtifactStore:
        Location: sambhav-test-cb-artifacts
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCodeRepo
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !Ref CodeStarConnection
                FullRepositoryId: sambhavgupta13/aws-serverless-app
                BranchName: main
                DetectChanges: true
              OutputArtifacts:
                - Name: SourceCodeStageAsZip
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildProjectBuildStage
              InputArtifacts:
                - Name: SourceCodeStageAsZip
              OutputArtifacts:
                - Name: BuildStageAsZip
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildProjectDeployStage
                EnvironmentVariables: !Sub '[{"name":"CODEPIPELINE_NAME","value":"${PipelineProjectName}" ,"type":"PLAINTEXT"}]'
              InputArtifacts:
                - Name: BuildStageAsZip
      DisableInboundStageTransitions:
        - Reason: Manual approval required
          StageName: Deploy      
              
             
Outputs:
  CodePipeline:
    Description: "AWS CodePipeline pipeline name"
    Value: !Ref Pipeline
  CodeStarConnectionArn:
    Description: "codestarconnection arn"
    Value: !GetAtt CodeStarConnection.ConnectionArn
