---
AWSTemplateFormatVersion: 2010-09-09
Description: "App resources"



Resources:
 FrontEndS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: 'static-assets-bucket-sambhav'

 TestBucket1:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    BucketName: 'test-bucket-1-sambhav'

 TestBucket2:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    BucketName: 'test-bucket-2-sambhav'
  
             
              
                  

